# **Identifiying Missing Values in Tabular Data**

### **Create CSV data file**

In [ ]:
import pandas as pd
from io import StringIO

csv_data = \
''''A,B,C,D
1.0, 2.0, 3.0, 4.0
5.0, 6.0,, 8.0
10.0,11.0,12.0,'''

csv_data

"'A,B,C,D\n1.0, 2.0, 3.0, 4.0\n5.0, 6.0,, 8.0\n10.0,11.0,12.0,"

Create Pandas DataFrame  from the `csv_data`

In [ ]:
df = pd.read_csv(StringIO(csv_data))
df

     'A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [ ]:
df.isnull()

      'A      B      C      D
0  False  False  False  False
1  False  False   True  False
2  False  False  False   True

In [ ]:
df.isnull().sum()

'A    0
B     0
C     1
D     1
dtype: int64

Convert dataframe into NumPy Array using the .values method on the df table

In [ ]:
import numpy as np

df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])

### **Eliminating Training example or features with missing values**

In [ ]:
df

     'A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [ ]:
df.dropna(axis=0)

    'A    B    C    D
0  1.0  2.0  3.0  4.0

In [ ]:
df.dropna(axis=1)

     'A     B
0   1.0   2.0
1   5.0   6.0
2  10.0  11.0

Handling Categorical data

Categroical data encoding with pandas

create data frame

In [ ]:
import pandas as pd
df = pd.DataFrame([['green', 'M', 10.1, 'class1'],
                   ['red', 'L', 13.5, 'class2'],
                   ['blue', 'XL', 15.3, 'class1']])

df

       0   1     2       3
0  green   M  10.1  class1
1    red   L  13.5  class2
2   blue  XL  15.3  class1

labeling columns names using the `.columns` function

In [ ]:
df.columns = ['color', 'size', 'price', 'classlabel']
df

   color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1

mapping ordinal feature

In [ ]:
size_mapping = {'XL': 3,
                'L' : 2,
                'M' : 1}

size_mapping

{'XL': 3, 'L': 2, 'M': 1}

In [ ]:
df['size'] = df['size'].map(size_mapping)
df

   color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   blue     3   15.3     class1

encoding class labels

mapping categorical labels to values

In [ ]:
import numpy as np

class_mapping = {label: idx for idx, label in
                 enumerate(np.unique(df['classlabel']))}
class_mapping

{'class1': 0, 'class2': 1}

In [ ]:
df['classlabel'] = df['classlabel'].map(class_mapping)
df

   color  size  price  classlabel
0  green     1   10.1           0
1    red     2   13.5           1
2   blue     3   15.3           0

reverse the mapping of values back to their original categoriacl labels.

In [ ]:
inverse_class_mapping = {idx: label for label, idx in class_mapping.items()}
df['classlabel'] = df['classlabel'].map(inverse_class_mapping)
df

   color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   blue     3   15.3     class1

performing one-hot encoding on nominal feature

In [ ]:
from sklearn.preprocessing import LabelEncoder

x = df[['color', 'size', 'price']].values
color_le = LabelEncoder()
x[:, 0] = color_le.fit_transform(x[:, 0])
x

array([[1, 1, 10.1],
       [2, 2, 13.5],
       [0, 3, 15.3]], dtype=object)

### **Partitioning a dataset into a sepaate training and test datasets**

Load Wine data from the UCI ML Repo

In [ ]:
df_wine = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)
df_wine

     0      1     2     3     4    5   ...    8     9      10    11    12    13
0     1  14.23  1.71  2.43  15.6  127  ...  0.28  2.29   5.64  1.04  3.92  1065
1     1  13.20  1.78  2.14  11.2  100  ...  0.26  1.28   4.38  1.05  3.40  1050
2     1  13.16  2.36  2.67  18.6  101  ...  0.30  2.81   5.68  1.03  3.17  1185
3     1  14.37  1.95  2.50  16.8  113  ...  0.24  2.18   7.80  0.86  3.45  1480
4     1  13.24  2.59  2.87  21.0  118  ...  0.39  1.82   4.32  1.04  2.93   735
..   ..    ...   ...   ...   ...  ...  ...   ...   ...    ...   ...   ...   ...
173   3  13.71  5.65  2.45  20.5   95  ...  0.52  1.06   7.70  0.64  1.74   740
174   3  13.40  3.91  2.48  23.0  102  ...  0.43  1.41   7.30  0.70  1.56   750
175   3  13.27  4.28  2.26  20.0  120  ...  0.43  1.35  10.20  0.59  1.56   835
176   3  13.17  2.59  2.37  20.0  120  ...  0.53  1.46   9.30  0.60  1.62   840
177   3  14.13  4.10  2.74  24.5   96  ...  0.56  1.35   9.20  0.61  1.60   560

[178 rows x 14 columns]

Relabel the column name

In [ ]:
df_wine.columns = ['Class label', 'Alcohol', 'Malic acid', 'Ash',
                   'Alcalinity of ash', 'Magnesium',
                   'Total phenols', 'Flavanoids', 'Nonflavanoid phenols',
                   'Proanthocyanins','Color intensity', 'Hue',
                   'OD280/OD315 of diluted wines','Proline']
df_wine

     Class label  Alcohol  ...  OD280/OD315 of diluted wines  Proline
0              1    14.23  ...                          3.92     1065
1              1    13.20  ...                          3.40     1050
2              1    13.16  ...                          3.17     1185
3              1    14.37  ...                          3.45     1480
4              1    13.24  ...                          2.93      735
..           ...      ...  ...                           ...      ...
173            3    13.71  ...                          1.74      740
174            3    13.40  ...                          1.56      750
175            3    13.27  ...                          1.56      835
176            3    13.17  ...                          1.62      840
177            3    14.13  ...                          1.60      560

[178 rows x 14 columns]

Perform the Actual data splitting

In [ ]:
from sklearn.model_selection import train_test_split